concurrency:
  cancel-in-progress: true
  group: api-test-${{ github.event.pull_request.number || github.ref }}
jobs:
  api-test:
    env:
      RECORDING_PATH: /tmp/recording-${{ matrix.case.name }}
    name: ${{ matrix.case.name }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-api-test
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: Download Docker Images
      uses: actions/download-artifact@v2
      with:
        name: standalone-image
        path: /tmp
    - continue-on-error: true
      name: Load Docker Images
      run: 'docker load -i /tmp/standalone-image.tar

        '
    - continue-on-error: true
      name: Run Test
      run: "./mvnw -B -f dolphinscheduler-api-test/pom.xml -am \\\n  -DfailIfNoTests=false\
        \ \\\n  -Dspotless.skip=false \\\n  -Dtest=${{ matrix.case.class }} test\n"
    - continue-on-error: true
      if: always()
      name: Upload Recording
      uses: actions/upload-artifact@v2
      with:
        name: recording-${{ matrix.case.name }}
        path: ${{ env.RECORDING_PATH }}
        retention-days: 1
    strategy:
      matrix:
        case:
        - class: org.apache.dolphinscheduler.api.test.cases.TenantAPITest
          name: Tenant
        - class: org.apache.dolphinscheduler.api.test.cases.WorkerGroupAPITest
          name: WorkerGroup
        - class: org.apache.dolphinscheduler.api.test.cases.ProjectAPITest
          name: Project
        - class: org.apache.dolphinscheduler.api.test.cases.ProcessDefinitionAPITest
          name: Workflow
        - class: org.apache.dolphinscheduler.api.test.cases.SchedulerAPITest
          name: Scheduler
        - class: org.apache.dolphinscheduler.api.test.cases.ExecutorAPITest
          name: Executor
        - class: org.apache.dolphinscheduler.api.test.cases.ProcessInstanceAPITest
          name: ProcessInstance
    timeout-minutes: 30
  build:
    if: ${{ (needs.paths-filter.outputs.not-ignore == 'true') || (github.event_name
      == 'push') }}
    name: API-Test-Build
    needs: paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Sanity Check
      uses: ./.github/actions/sanity-check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-api-test
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: Build Image
      run: './mvnw -B clean install \

        -Dmaven.test.skip \

        -Dmaven.javadoc.skip \

        -Dspotless.skip=true \

        -Pdocker,release -Ddocker.tag=ci

        '
    - continue-on-error: true
      name: Export Docker Images
      run: 'docker save apache/dolphinscheduler-standalone-server:ci -o /tmp/standalone-image.tar
        \

        && du -sh /tmp/standalone-image.tar

        '
    - continue-on-error: true
      name: Upload Docker Images
      uses: actions/upload-artifact@v2
      with:
        name: standalone-image
        path: /tmp/standalone-image.tar
        retention-days: 1
    timeout-minutes: 20
  paths-filter:
    name: API-Test-Path-Filter
    outputs:
      not-ignore: ${{ steps.filter.outputs.not-ignore }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
      with:
        filters: "not-ignore:\n  - '!(docs/**)'\n"
  result:
    if: always()
    name: API-Test-Result
    needs:
    - api-test
    - paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Status
      run: "if [[ ${{ needs.paths-filter.outputs.not-ignore }} == 'false' && ${{ github.event_name\
        \ }} == 'pull_request' ]]; then\n  echo \"Skip API Test!\"\n  exit 0\nfi\n\
        if [[ ${{ needs.api-test.result }} != 'success' ]]; then\n  echo \"API test\
        \ Failed!\"\n  exit -1\nfi\n"
    timeout-minutes: 30
name: API-Test
on:
  repository_dispatch:
    types: trigger-ga___api-test.yml
