concurrency:
  cancel-in-progress: true
  group: doc-${{ github.event.pull_request.number || github.ref }}
jobs:
  dead-link:
    if: (github.event_name == 'schedule' && github.repository == 'apache/dolphinscheduler')
      || (github.event_name != 'schedule')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      run: sudo npm install -g markdown-link-check@3.11.2
    - continue-on-error: true
      run: sudo apt install plocate -y
    - continue-on-error: true
      run: "for file in $(locate \"$PWD*/*.md\" | grep -v ./deploy/terraform/aws/README.md);\
        \ do\n  markdown-link-check -c .dlc.json -q \"$file\" &\ndone\nwait\n"
    timeout-minutes: 30
  helm-doc:
    if: ${{ (needs.paths-filter.outputs.helm-doc == 'true') || (github.event_name
      == 'push') }}
    name: Helm-Doc-Execute
    needs: paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Generating helm-doc
      run: './mvnw validate -P helm-doc -pl :dolphinscheduler

        '
    - continue-on-error: true
      name: Check helm-doc
      run: "DIFF=$(git diff ${GITHUB_WORKSPACE}/deploy/kubernetes/*md)\nif [ ! -z\
        \ \"$DIFF\" ]; then\n    echo \"###### ERROR: helm-doc is not up to date ######\"\
        \n    echo \"Please execute './mvnw validate -P helm-doc -pl :dolphinscheduler'\
        \ in your clone, of your fork, of the project, and commit an updated deploy/kubernetes/README.md\
        \ for the chart.\"\n    echo \"###### ERROR: helm-doc is not up to date ######\"\
        \nfi\ngit diff --exit-code\n"
    timeout-minutes: 20
  img-check:
    defaults:
      run:
        working-directory: docs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - continue-on-error: true
      name: Run Dev Relative Reference
      run: python img_utils.py -v dev-syntax
    - continue-on-error: true
      name: Run Image Check
      run: python img_utils.py -v check
    timeout-minutes: 15
  paths-filter:
    name: Helm-Doc-Path-Filter
    outputs:
      helm-doc: ${{ steps.filter.outputs.helm-doc }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
      with:
        filters: "helm-doc:\n  - 'deploy/**'\n"
  result:
    if: always()
    name: Docs
    needs:
    - style
    - img-check
    - dead-link
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Status
      run: "if [[ ${{ contains(needs.*.result, 'failure') }} == 'true' || ${{ contains(needs.*.result,\
        \ 'cancelled') }} == 'true' ]]; then\n  echo \"Build Failed!\"\n  exit 1\n\
        else\n  echo \"Build Success!\"\nfi\n"
    timeout-minutes: 30
  style:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Style Check
      run: ./mvnw spotless:check
    timeout-minutes: 10
name: Docs
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
