concurrency:
  cancel-in-progress: true
  group: e2e-${{ github.event.pull_request.number || github.ref }}
jobs:
  build:
    if: ${{ (needs.paths-filter.outputs.not-ignore == 'true') || (github.event_name
      == 'push') }}
    name: E2E-Build
    needs: paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Sanity Check
      uses: ./.github/actions/sanity-check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-e2e
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: Build Image
      run: './mvnw -B clean install \

        -Dmaven.test.skip \

        -Dmaven.javadoc.skip \

        -Dspotless.skip=true \

        -Pdocker,release -Ddocker.tag=ci \

        -pl dolphinscheduler-standalone-server -am

        '
    - continue-on-error: true
      name: Export Docker Images
      run: 'docker save apache/dolphinscheduler-standalone-server:ci -o /tmp/standalone-image.tar
        \

        && du -sh /tmp/standalone-image.tar

        '
    - continue-on-error: true
      name: Upload Docker Images
      uses: actions/upload-artifact@v2
      with:
        name: standalone-image
        path: /tmp/standalone-image.tar
        retention-days: 1
    timeout-minutes: 20
  e2e:
    env:
      RECORDING_PATH: /tmp/recording-${{ matrix.case.name }}
    name: ${{ matrix.case.name }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-e2e
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: Download Docker Images
      uses: actions/download-artifact@v2
      with:
        name: standalone-image
        path: /tmp
    - continue-on-error: true
      name: Load Docker Images
      run: 'docker load -i /tmp/standalone-image.tar

        '
    - continue-on-error: true
      name: Run Test
      run: "./mvnw -B -f dolphinscheduler-e2e/pom.xml -am \\\n  -DfailIfNoTests=false\
        \ \\\n  -Dtest=${{ matrix.case.class }} test\n"
    - continue-on-error: true
      if: always()
      name: Upload Recording
      uses: actions/upload-artifact@v2
      with:
        name: recording-${{ matrix.case.name }}
        path: ${{ env.RECORDING_PATH }}
        retention-days: 1
    strategy:
      matrix:
        case:
        - class: org.apache.dolphinscheduler.e2e.cases.TenantE2ETest
          name: Tenant
        - class: org.apache.dolphinscheduler.e2e.cases.UserE2ETest
          name: User
        - class: org.apache.dolphinscheduler.e2e.cases.WorkerGroupE2ETest
          name: WorkerGroup
        - class: org.apache.dolphinscheduler.e2e.cases.ProjectE2ETest
          name: Project
        - class: org.apache.dolphinscheduler.e2e.cases.QueueE2ETest
          name: Queue
        - class: org.apache.dolphinscheduler.e2e.cases.EnvironmentE2ETest
          name: Environment
        - class: org.apache.dolphinscheduler.e2e.cases.ClusterE2ETest
          name: Cluster
        - class: org.apache.dolphinscheduler.e2e.cases.TokenE2ETest
          name: Token
        - class: org.apache.dolphinscheduler.e2e.cases.WorkflowE2ETest
          name: Workflow
        - class: org.apache.dolphinscheduler.e2e.cases.WorkflowHttpTaskE2ETest
          name: WorkflowHttp
        - class: org.apache.dolphinscheduler.e2e.cases.WorkflowJavaTaskE2ETest
          name: WorkflowJava
        - class: org.apache.dolphinscheduler.e2e.cases.FileManageE2ETest
          name: FileManage
        - class: org.apache.dolphinscheduler.e2e.cases.UdfManageE2ETest
          name: UdfManage
        - class: org.apache.dolphinscheduler.e2e.cases.FunctionManageE2ETest
          name: FunctionManage
        - class: org.apache.dolphinscheduler.e2e.cases.MysqlDataSourceE2ETest
          name: MysqlDataSource
        - class: org.apache.dolphinscheduler.e2e.cases.ClickhouseDataSourceE2ETest
          name: ClickhouseDataSource
        - class: org.apache.dolphinscheduler.e2e.cases.PostgresDataSourceE2ETest
          name: PostgresDataSource
    timeout-minutes: 30
  e2e-optional:
    env:
      RECORDING_PATH: /tmp/recording-${{ matrix.case.name }}
    name: ${{ matrix.case.name }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-e2e
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: Download Docker Images
      uses: actions/download-artifact@v2
      with:
        name: standalone-image
        path: /tmp
    - continue-on-error: true
      name: Load Docker Images
      run: 'docker load -i /tmp/standalone-image.tar

        '
    - continue-on-error: true
      name: Run Test
      run: "./mvnw -B -f dolphinscheduler-e2e/pom.xml -am \\\n  -DfailIfNoTests=false\
        \ \\\n  -Dtest=${{ matrix.case.class }} test\n"
    - continue-on-error: true
      if: always()
      name: Upload Recording
      uses: actions/upload-artifact@v2
      with:
        name: recording-${{ matrix.case.name }}
        path: ${{ env.RECORDING_PATH }}
        retention-days: 1
    strategy:
      matrix:
        case:
        - class: org.apache.dolphinscheduler.e2e.cases.SqlServerDataSourceE2ETest
          name: SqlServerDataSource
        - class: org.apache.dolphinscheduler.e2e.cases.HiveDataSourceE2ETest
          name: HiveDataSource
    timeout-minutes: 30
  paths-filter:
    name: E2E-Path-Filter
    outputs:
      not-ignore: ${{ steps.filter.outputs.not-ignore }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
      with:
        filters: "not-ignore:\n  - '!(docs/**)'\n"
  result:
    if: always()
    name: E2E
    needs:
    - e2e
    - paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Status
      run: "if [[ ${{ needs.paths-filter.outputs.not-ignore }} == 'false' && ${{ github.event_name\
        \ }} == 'pull_request' ]]; then\n  echo \"Skip E2E!\"\n  exit 0\nfi\nif [[\
        \ ${{ needs.e2e.result }} != 'success' ]]; then\n  echo \"E2E Failed!\"\n\
        \  exit -1\nfi\n"
    timeout-minutes: 30
name: E2E
on:
  repository_dispatch:
    types: trigger-ga___e2e.yml
