concurrency:
  cancel-in-progress: true
  group: frontend-${{ github.event.pull_request.number || github.ref }}
defaults:
  run:
    working-directory: dolphinscheduler-ui
jobs:
  build:
    if: ${{ (needs.paths-filter.outputs.not-ignore == 'true') || (github.event_name
      == 'push') }}
    name: Build
    needs: paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest'
      name: Sanity Check
      uses: ./.github/actions/sanity-check
    - continue-on-error: true
      name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - continue-on-error: true
      name: Compile and Build on ${{ matrix.os }}
      run: 'set -x

        npm install pnpm@7 -g

        pnpm install

        pnpm run lint

        pnpm run build:prod

        '
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    timeout-minutes: 30
  paths-filter:
    name: Frontend-Path-Filter
    outputs:
      not-ignore: ${{ steps.filter.outputs.not-ignore }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
      with:
        filters: "not-ignore:\n  - '!(docs/**)'\n"
  result:
    if: always()
    name: Frontend Build
    needs:
    - build
    - paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Status
      run: "if [[ ${{ needs.paths-filter.outputs.not-ignore }} == 'false' && ${{ github.event_name\
        \ }} == 'pull_request' ]]; then\n  echo \"Skip Frontend Build!\"\n  exit 0\n\
        fi\nif [[ ${{ needs.build.result }} != 'success' ]]; then\n  echo \"Frontend\
        \ Build Failed!\"\n  exit -1\nfi\n"
    timeout-minutes: 30
name: Frontend
on:
  repository_dispatch:
    types: trigger-ga___frontend.yml
