jobs:
  issueRobot:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }}
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: true
    - continue-on-error: true
      name: Translation into English in issue
      uses: ./.github/actions/translate-on-issue
      with:
        translate-body: true
        translate-title: true
    - continue-on-error: true
      name: Comment in issue
      uses: ./.github/actions/comment-on-issue
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: 'Thank you for your feedback, we have received your issue, Please
          wait patiently for a reply.

          * In order for us to understand your request as soon as possible, please
          provide detailed information, version or pictures.

          * If you haven''t received a reply for a long time, you can [join our slack](https://s.apache.org/dolphinscheduler-slack)
          and send your question to channel `#troubleshooting`

          '
name: issue-robot
on:
  repository_dispatch:
    types: trigger-ga___issue-robot.yml
