jobs:
  result:
    name: 'Mergeable: milestone-label-check'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Status
      run: 'echo "Temporary skipping this check"

        '
    timeout-minutes: 30
name: Mergeable
on:
  repository_dispatch:
    types: trigger-ga___mergeable.yml
