env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      name: Run OWASP Dependency Check
      run: ./mvnw -B clean install verify dependency-check:check -DskipDepCheck=false
        -Dmaven.test.skip=true -Dspotless.skip=true
    - continue-on-error: true
      if: ${{ cancelled() || failure() }}
      name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: dependency report
        path: target/dependency-check-report.html
name: OWASP Dependency Check
on:
  repository_dispatch:
    types: trigger-ga___owasp-dependency-check.yaml
