jobs:
  pullRequestTargetRobot:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }}
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: true
    - continue-on-error: true
      name: Label in pull request
      uses: actions/labeler@v4
      with:
        configuration-path: .github/actions/labeler/labeler.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true
    - continue-on-error: true
      name: Auto assign in pull request
      uses: ./.github/actions/auto-assign-action
      with:
        configuration-path: .github/actions/auto-assign/auto-assign.yml
    timeout-minutes: 10
name: pull-request-target-robot
on:
  repository_dispatch:
    types: trigger-ga___pull-request-target-robot.yml
