jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v4
      with:
        close-issue-message: 'This issue has been closed because it has not received
          response for too long time. You could reopen it if you encountered similar
          problems in the future.

          '
        close-pr-message: 'This pull request has been closed because it has not had
          recent activity. You could reopen it if you try to continue your work, and
          anyone who are interested in it are encouraged to continue work on this
          pull request.

          '
        days-before-issue-close: 7
        days-before-issue-stale: 30
        days-before-pr-close: 7
        days-before-pr-stale: 120
        exempt-issue-labels: Waiting for reply,feature,DSIP,security,roadmap
        stale-issue-message: 'This issue has been automatically marked as stale because
          it has not had recent activity for 30 days. It will be closed in next 7
          days if no further activity occurs.

          '
        stale-pr-message: 'This pull request has been automatically marked as stale
          because it has not had recent activity for 120 days. It will be closed in
          7 days if no further activity occurs.

          '
name: Close stale issues and PRs
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  issues: write
  pull-requests: write
