concurrency:
  cancel-in-progress: true
  group: unit-test-${{ github.event.pull_request.number || github.ref }}
env:
  LOG_DIR: /tmp/dolphinscheduler
jobs:
  paths-filter:
    name: Unit-Test-Path-Filter
    outputs:
      not-ignore: ${{ steps.filter.outputs.not-ignore }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
      with:
        filters: "not-ignore:\n  - '!(docs/**)'\n"
  result:
    if: always()
    name: Unit Test
    needs:
    - unit-test
    - paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Status
      run: "if [[ ${{ needs.paths-filter.outputs.not-ignore }} == 'false' && ${{ github.event_name\
        \ }} == 'pull_request' ]]; then\n  echo \"Skip Unit Test!\"\n  exit 0\nfi\n\
        if [[ ${{ needs.unit-test.result }} != 'success' ]]; then\n  echo \"Unit Test\
        \ Failed!\"\n  exit -1\nfi\n"
    timeout-minutes: 30
  unit-test:
    if: ${{ (needs.paths-filter.outputs.not-ignore == 'true') || (github.event_name
      == 'push') }}
    name: Unit-Test
    needs: paths-filter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: true
    - continue-on-error: true
      name: Sanity Check
      uses: ./.github/actions/sanity-check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-unit-test
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: Run Unit tests
      run: ./mvnw clean verify -B -Dmaven.test.skip=false -Dspotless.skip=true -DskipUT=false
    - continue-on-error: true
      name: Upload coverage report to codecov
      run: CODECOV_TOKEN="09c2663f-b091-4258-8a47-c981827eb29a" bash <(curl -s https://codecov.io/bash)
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Run SonarCloud Analysis
      run: './mvnw --batch-mode verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        -Dmaven.test.skip=true -Dspotless.skip=true -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=apache -Dsonar.core.codeCoveragePlugin=jacoco -Dsonar.projectKey=apache-dolphinscheduler
        -Dsonar.login=e4058004bc6be89decf558ac819aa1ecbee57682 -Dsonar.exclusions=,dolphinscheduler-ui/src/**/i18n/locale/*.js,dolphinscheduler-microbench/src/**/*
        -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -DskipUT=true

        '
    strategy:
      matrix:
        java:
        - '8'
        - '11'
    timeout-minutes: 45
name: Test
on:
  repository_dispatch:
    types: trigger-ga___unit-test.yml
